# 如果你的显卡不太差，可以使用这个内建的方案high-quality，  fast会更快


profile=high-quality

# 标题显示不带后缀的文件名，如果不设置，默认优先文件属性中的标题，可能不是文件名
title=${filename/no-ext}

# 在屏幕控制器 [OSC] 中显示文件名而不是标题名
script-opts='osc-title=${filename}'

#启动默认音量

volume=100
volume-max=150


#开启缓存
cache=yes
cache-on-disk=no
#缓存时间
#cache-secs=30


#禁用内置快捷键方案，builtin与default相比不影响脚本的预设快捷键
no-input-builtin-bindings


# 记住上次播放的位置
save-position-on-quit=yes

# 外观 Appearance

#设置默认打开的窗口大小geometry=3840x2160或 geometry=100%  设置高度-1，是为了在全屏后鼠标移到底部还能唤出被隐藏的任务栏   
geometry=3840x2159  
#fullscreen # 启动时全屏。
osd-on-seek=msg # Seek 时显示 osd-msg3 而非进度条。

#无边框
border=no
#拖入文件行为设置（no/auto/replace/append)。no禁用拖入，auto根据平台自动选择，replace替换当前文件并播放，append将拖入的文件添加到播放列表。默认是拖入replace，按住shift拖入append
drag-and-drop=no



#osd-bar边框大小，mpv0.37.0之后版本加入此选项
osd-bar-border-size=0
#osd-bar宽度[1,100],屏幕宽度的百分比
osd-bar-w=100
#osd-bar高度[0.1,50]屏幕高度的百分比
osd-bar-h=0.3
#位置[-1,1]x为左到右，y为上到下
osd-bar-align-y=1

#设置OSD文本信息的持续时间（毫秒）
osd-duration=2000
#OSD随窗口大小缩放
osd-scale-by-window=no






# 失去焦点自动暂停
[pause_on_focus_lost]
profile-cond=not focused
profile-restore=copy-equal
pause=yes

# 多声道音频规格化
audio-normalize-downmix=yes



## 音频API
ao=wasapi #Windows最佳音频api：wasapi

# 用于插件 https://github.com/natural-harmonia-gropius/input-event   
input-doubleclick-time=200


# 让进度条点击直接跳到“最近关键帧”，而不是插值
#osc-seekmode=relative+exact   # 拖动时仍用关键帧，但单击立即跳转

# 启用多线程解码（根据CPU核心数调整）
#threads=8  # 4核CPU建议设为4
# 为高帧率视频增加解码缓存
 # hwdec-extra-frames=64


# 是否直接解码到显存
opengl-pbo=yes



# 1. 关键帧 seek 只向前找最近的关键帧，速度最快
#hr-seek=no
# 2. 强制每次 seek 都落到关键帧，进一步减少等待
cache-seek-minimal=yes


# 必须先开启 display-resample 才能使用插帧
video-sync=display-resample
# 开启平滑插帧（大幅减少画面平移时的抖动感）
interpolation=yes
# 设置插帧算法（oversample 性能消耗适中且效果极佳，显卡极强也可尝试 sphinx 或 tbox）
tscale=oversample
# 允许在绝对精确定位（hr-seek）过程中丢帧，以加快响应速度
hr-seek-framedrop=yes



# 亮度放大算法（极大地提升画面锐度）
scale=ewa_lanczossharp
# 色度放大算法（让色彩边缘更清晰，不溢色）
cscale=ewa_lanczossharp
# 缩小算法（保持画面自然，防止过度锐化产生的锯齿）
dscale=mitchell
# 针对显卡性能极强，开启更高精度的内部色彩运算
vd-lavc-dr=yes

# 尝试使用硬解的格式(默认h264,vc1,hevc,vp8,vp9,av1；all是特殊值指全部格式)
hwdec-codecs=all 



#glsl-shaders="~~/shaders/ArtCNN_C4F32.glsl"


# 添加了profile-cond条件判断开启的预设不需要在开头加profile=4K
[4K]
profile-desc=
profile-cond=height>2000
gpu-api=d3d11
gpu-context=d3d11
hwdec=d3d11va
# 自动隐藏鼠标
cursor-autohide=500
# 最大向后缓存大小(默认 150MiB)
demuxer-max-bytes=150MiB
# 最大允许保留的已播放的内容的数据大小(默认 50MiB)
demuxer-max-back-bytes=50MiB
#视频输出驱动，Windows可选gpu/gpu-next/direct3d等，gpu最成熟稳定（），gpu-next为实验性，direct3d只在为兼容老旧系统硬件时使用
vo=gpu-next



[1080P]
profile-desc=
profile-cond=height<=2000
#   vulkan、d3d11及opengl都可选。三者理论上vulkan性能最好，但依然推荐d3d11。
gpu-api=vulkan
#   <d3d11|winvk>
gpu-context=winvk
# 设置硬解api，# <no|d3d11va|d3d11va-copy|dxva2-copy|nvdec|nvdec-copy|vulkan|vulkan-copy>   auto-copy auto-safe      amd显卡：vaapi vaapi-copy
hwdec=vulkan-copy
#视频输出驱动，Windows可选gpu/gpu-next/direct3d等，gpu最成熟稳定（），gpu-next为实验性，direct3d只在为兼容老旧系统硬件时使用
vo=gpu-next


# 自动隐藏鼠标
cursor-autohide=500
# 最大向后缓存大小(默认 150MiB)
demuxer-max-bytes=50MiB
# 最大允许保留的已播放的内容的数据大小(默认 50MiB)
demuxer-max-back-bytes=20MiB

# 开启内置软锐化滤镜
# luma_amount 为锐化强度，推荐在 0.2 到 0.6 之间尝试 (默认 0.0 为不锐化)
vf-append=unsharp=luma_msize_x=3:luma_msize_y=3:luma_amount=1
# 色彩调节
# vf-append=lavfi=eq=brightness=0.1:contrast=1.2:saturation=1.1:gamma=1.1




# 开启rtx超分辨率
#vf=d3d11vpp=scale=2:scaling-mode=nvidia




